version: "3.8"

services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_register
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "8083:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build: .
    container_name: php-container
    ports:
      - "8082:80"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: student_register
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
