version: "3.8"

services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_register
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "8083:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  php:
    build: .
    container_name: php-container
    ports:
      - "8082:80"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: student_register
    volumes:
      - .:/var/www/html
      - ./uploads:/var/www/html/uploads  # Mount directory for file uploads
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
